In [4]:
import numpy as np

## Data Types of Numpy

In [5]:
# Numpys Main datatype is ndarray

In [6]:
arr = np.array([1,2,3,4,5])

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr.shape

(5,)

In [9]:
arr.ndim

1

In [10]:
random_array = np.random.randint(10,size=(2,3,4,5))

In [11]:
random_array

array([[[[1, 1, 9, 3, 4],
         [4, 2, 2, 5, 5],
         [9, 9, 3, 6, 0],
         [6, 7, 6, 8, 3]],

        [[3, 9, 3, 4, 6],
         [2, 4, 0, 5, 2],
         [1, 6, 4, 2, 3],
         [8, 0, 0, 8, 0]],

        [[0, 1, 0, 0, 9],
         [1, 7, 5, 7, 8],
         [3, 9, 5, 2, 2],
         [4, 8, 9, 0, 1]]],


       [[[5, 0, 1, 0, 4],
         [7, 2, 3, 0, 1],
         [5, 2, 6, 4, 1],
         [2, 0, 2, 6, 5]],

        [[2, 8, 2, 4, 0],
         [9, 2, 4, 1, 9],
         [8, 0, 7, 0, 2],
         [1, 0, 3, 0, 9]],

        [[8, 8, 4, 0, 0],
         [7, 8, 8, 4, 5],
         [7, 4, 9, 7, 2],
         [4, 0, 9, 1, 5]]]])

In [16]:
array = np.random.randint(5 ,size=(2,5))

In [17]:
array

array([[3, 1, 0, 0, 4],
       [2, 1, 2, 3, 0]])

In [38]:
array2 = np.random.randint(5,size = (5,2))
array2

array([[2, 1],
       [2, 1],
       [2, 0],
       [2, 2],
       [2, 0]])

In [41]:
array2.reshape
#array2 * array

<function ndarray.reshape>

In [18]:
array.shape

(2, 5)

In [19]:
array.T

array([[3, 2],
       [1, 1],
       [0, 2],
       [0, 3],
       [4, 0]])

In [20]:
array

array([[3, 1, 0, 0, 4],
       [2, 1, 2, 3, 0]])

In [21]:
array dot(array.T)

SyntaxError: invalid syntax (<ipython-input-21-241ddaebcb80>, line 1)

In [24]:
dot_array = np.dot(array,array.T)

In [25]:
dot_array.shape

(2, 2)

In [26]:
dot_array.ndim

2

In [34]:
random_array = np.random.rand(2,3,4)

In [35]:
random_array

array([[[0.24695527, 0.8508272 , 0.58863649, 0.50282674],
        [0.89569081, 0.87038812, 0.07043088, 0.21821306],
        [0.51001315, 0.6967767 , 0.43453007, 0.85793122]],

       [[0.57606001, 0.24625435, 0.52065885, 0.41161325],
        [0.73348595, 0.1848901 , 0.17387076, 0.33067576],
        [0.80303687, 0.70846725, 0.80376179, 0.19849164]]])

In [42]:
arr1 = np.arange(1,10,2) 

In [43]:
arr1

array([1, 3, 5, 7, 9])

In [47]:
<img src="panda.png"/>

SyntaxError: invalid syntax (<ipython-input-47-2ffd334afd26>, line 1)

In [48]:
from matplotlib.image import imread

In [49]:
panda = imread('panda.png')

In [51]:
type(panda)

numpy.ndarray